# Generated by Django 5.0.14 on 2025-06-22 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_code', models.AutoField(primary_key=True, serialize=False, verbose_name='رمز نوع الإجازة')),
                ('leave_type_name', models.CharField(max_length=100, unique=True, verbose_name='اسم نوع الإجازة')),
                ('leave_type_name_en', models.CharField(blank=True, max_length=100, verbose_name='اسم نوع الإجازة بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة الأجر')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='تتطلب موافقة')),
                ('requires_medical_certificate', models.BooleanField(default=False, verbose_name='تتطلب شهادة طبية')),
                ('calculation_method', models.CharField(choices=[('fixed', 'ثابت'), ('monthly', 'شهري'), ('yearly', 'سنوي'), ('service_based', 'حسب سنوات الخدمة')], default='yearly', max_length=15, verbose_name='طريقة الحساب')),
                ('default_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الرصيد الافتراضي')),
                ('max_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الحد الأقصى للرصيد')),
                ('min_days_per_request', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للأيام في الطلب')),
                ('max_days_per_request', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للأيام في الطلب')),
                ('max_requests_per_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للطلبات في السنة')),
                ('min_advance_notice_days', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للإشعار المسبق (أيام)')),
                ('gender_restriction', models.CharField(choices=[('all', 'الجميع'), ('male', 'ذكور فقط'), ('female', 'إناث فقط')], default='all', max_length=10, verbose_name='قيود الجنس')),
                ('exclude_weekends', models.BooleanField(default=True, verbose_name='استبعاد عطل نهاية الأسبوع')),
                ('exclude_holidays', models.BooleanField(default=True, verbose_name='استبعاد العطل الرسمية')),
                ('allow_carryover', models.BooleanField(default=False, verbose_name='السماح بالترحيل')),
                ('max_carryover_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الحد الأقصى لأيام الترحيل')),
                ('carryover_expiry_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='انتهاء صلاحية الترحيل (شهور)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'db_table': 'leave_management_leave_type',
                'ordering': ['leave_type_name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم السياسة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='leave_policies/', verbose_name='وثيقة السياسة')),
                ('applies_to_all', models.BooleanField(default=True, verbose_name='تطبق على الجميع')),
                ('effective_from', models.DateField(verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('departments', models.ManyToManyField(blank=True, related_name='leave_policies', to='employee_management.department', verbose_name='الأقسام المحددة')),
                ('job_titles', models.ManyToManyField(blank=True, related_name='leave_policies', to='employee_management.jobtitle', verbose_name='الوظائف المحددة')),
            ],
            options={
                'verbose_name': 'سياسة إجازة',
                'verbose_name_plural': 'سياسات الإجازات',
                'db_table': 'leave_management_leave_policy',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة المتوقع')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة الفعلي')),
                ('requested_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام المطلوبة')),
                ('approved_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عدد الأيام الموافق عليها')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='جهة الاتصال في حالة الطوارئ')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='هاتف الطوارئ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='draft', max_length=15, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='leave_medical_certificates/', verbose_name='الشهادة الطبية')),
                ('employee_comments', models.TextField(blank=True, verbose_name='تعليقات الموظف')),
                ('admin_comments', models.TextField(blank=True, verbose_name='تعليقات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee_management.employee', verbose_name='الموظف')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='قدم بواسطة')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave_management.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'db_table': 'leave_management_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام المخصصة')),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام المستخدمة')),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام المعلقة')),
                ('carried_over_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام المرحلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee_management.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_balances', to='leave_management.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'db_table': 'leave_management_leave_balance',
                'ordering': ['-year', 'employee', 'leave_type'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم العطلة')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='اسم العطلة بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('holiday_type', models.CharField(choices=[('public', 'عطلة رسمية'), ('company', 'عطلة الشركة'), ('religious', 'عطلة دينية'), ('national', 'عطلة وطنية')], max_length=15, verbose_name='نوع العطلة')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='متكررة سنوياً')),
                ('affects_leave_calculation', models.BooleanField(default=True, verbose_name='تؤثر على حساب الإجازات')),
                ('applies_to_all', models.BooleanField(default=True, verbose_name='تطبق على الجميع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('departments', models.ManyToManyField(blank=True, related_name='holidays', to='employee_management.department', verbose_name='الأقسام المحددة')),
            ],
            options={
                'verbose_name': 'عطلة',
                'verbose_name_plural': 'العطل',
                'db_table': 'leave_management_holiday',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='leave_manag_date_6054eb_idx'), models.Index(fields=['holiday_type', 'is_active'], name='leave_manag_holiday_146b5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.PositiveIntegerField(default=1, verbose_name='مستوى الاعتماد')),
                ('action', models.CharField(choices=[('approve', 'موافقة'), ('reject', 'رفض'), ('request_info', 'طلب معلومات إضافية')], max_length=15, verbose_name='الإجراء')),
                ('comments', models.TextField(blank=True, verbose_name='التعليقات')),
                ('approved_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الأيام الموافق عليها')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave_management.leaverequest', verbose_name='طلب الإجازة')),
            ],
            options={
                'verbose_name': 'اعتماد إجازة',
                'verbose_name_plural': 'اعتمادات الإجازات',
                'db_table': 'leave_management_leave_approval',
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['leave_request', 'approval_level'], name='leave_manag_leave_r_34c60f_idx'), models.Index(fields=['approver', 'action_date'], name='leave_manag_approve_22b3a7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='leave_manag_employe_f1a010_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['leave_type', 'status'], name='leave_manag_leave_t_ddd251_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_manag_start_d_cd8666_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'submitted_at'], name='leave_manag_status_d72cec_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'year'], name='leave_manag_employe_2b429d_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['leave_type', 'year'], name='leave_manag_leave_t_3ddc77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
